[package]
name = "devdash-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
devdash-core = { version = "0.1.0", path = "../devdash-core" }
devdash-widgets = { version = "0.1.0", path = "../devdash-widgets" }
ratatui = "0.29.0"
